<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class FilesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (env('MIX_ENV_MODE') !== 'production') {
            DB::table('files')->insert([
                // KH1 Model1 Ver3
                [
                    'fileName' => 'MODEL1-3_DPT001_1_PROCESS001.pdf',
                    'pageNum' => 1,
                    'model' => 'MODEL1',
                    'version' => 3,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 1,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL1-3_DPT001_2_PROCESS001.pdf',
                    'pageNum' => 1,
                    'model' => 'MODEL1',
                    'version' => 3,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 2,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL1-3_DPT001_3_PROCESS001.pdf',
                    'pageNum' => 1,
                    'model' => 'MODEL1',
                    'version' => 3,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 3,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL1-3_DPT001_4_PROCESS001.pdf',
                    'pageNum' => 1,
                    'model' => 'MODEL1',
                    'version' => 3,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 4,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL1-3_DPT001_5_PROCESS001.pdf',
                    'pageNum' => 1,
                    'model' => 'MODEL1',
                    'version' => 3,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 5,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL1-3_DPT002_1_PROCESS002.pdf',
                    'pageNum' => 1,
                    'model' => 'MODEL1',
                    'version' => 3,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 1,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL1-3_DPT002_2_PROCESS002.pdf',
                    'pageNum' => 1,
                    'model' => 'MODEL1',
                    'version' => 3,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 2,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL1-3_DPT002_3_PROCESS002.pdf',
                    'pageNum' => 1,
                    'model' => 'MODEL1',
                    'version' => 3,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 3,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL1-3_DPT002_4_PROCESS002.pdf',
                    'pageNum' => 1,
                    'model' => 'MODEL1',
                    'version' => 3,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 4,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL1-3_DPT002_5_PROCESS002.pdf',
                    'pageNum' => 1,
                    'model' => 'MODEL1',
                    'version' => 3,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 5,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],

                [
                    'fileName' => 'MODEL1-3_DPT003_1_PROCESS003.pdf',
                    'pageNum' => 1,
                    'model' => 'MODEL1',
                    'version' => 3,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 1,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL1-3_DPT003_2_PROCESS003.pdf',
                    'pageNum' => 1,
                    'model' => 'MODEL1',
                    'version' => 3,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 2,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL1-3_DPT003_3_PROCESS003.pdf',
                    'pageNum' => 1,
                    'model' => 'MODEL1',
                    'version' => 3,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 3,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL1-3_DPT003_4_PROCESS003.pdf',
                    'pageNum' => 1,
                    'model' => 'MODEL1',
                    'version' => 3,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 4,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL1-3_DPT003_5_PROCESS003.pdf',
                    'pageNum' => 1,
                    'model' => 'MODEL1',
                    'version' => 3,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 5,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                // KH1 Model2 Ver1
                [
                    'fileName' => 'MODEL2-1_DPT001_1_PROCESS001.pdf',
                    'pageNum' => 2,
                    'model' => 'MODEL2',
                    'version' => 1,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 1,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-1_DPT001_2_PROCESS001.pdf',
                    'pageNum' => 2,
                    'model' => 'MODEL2',
                    'version' => 1,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 2,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-1_DPT001_3_PROCESS001.pdf',
                    'pageNum' => 2,
                    'model' => 'MODEL2',
                    'version' => 1,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 3,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-1_DPT001_4_PROCESS001.pdf',
                    'pageNum' => 2,
                    'model' => 'MODEL2',
                    'version' => 1,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 4,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-1_DPT001_5_PROCESS001.pdf',
                    'pageNum' => 2,
                    'model' => 'MODEL2',
                    'version' => 1,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 5,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-1_DPT002_1_PROCESS002.pdf',
                    'pageNum' => 2,
                    'model' => 'MODEL2',
                    'version' => 1,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 1,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-1_DPT002_2_PROCESS002.pdf',
                    'pageNum' => 2,
                    'model' => 'MODEL2',
                    'version' => 1,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 2,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-1_DPT002_3_PROCESS002.pdf',
                    'pageNum' => 2,
                    'model' => 'MODEL2',
                    'version' => 1,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 3,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-1_DPT002_4_PROCESS002.pdf',
                    'pageNum' => 2,
                    'model' => 'MODEL2',
                    'version' => 1,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 4,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-1_DPT002_5_PROCESS002.pdf',
                    'pageNum' => 2,
                    'model' => 'MODEL2',
                    'version' => 1,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 5,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-1_DPT003_1_PROCESS003.pdf',
                    'pageNum' => 2,
                    'model' => 'MODEL2',
                    'version' => 1,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 1,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-1_DPT003_2_PROCESS003.pdf',
                    'pageNum' => 2,
                    'model' => 'MODEL2',
                    'version' => 1,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 2,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-1_DPT003_3_PROCESS003.pdf',
                    'pageNum' => 2,
                    'model' => 'MODEL2',
                    'version' => 1,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 3,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-1_DPT003_4_PROCESS003.pdf',
                    'pageNum' => 2,
                    'model' => 'MODEL2',
                    'version' => 1,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 4,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-1_DPT003_5_PROCESS003.pdf',
                    'pageNum' => 2,
                    'model' => 'MODEL2',
                    'version' => 1,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 5,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                // KH1 Model2 Ver2
                [
                    'fileName' => 'MODEL2-2_DPT001_1_PROCESS001.pdf',
                    'pageNum' => 3,
                    'model' => 'MODEL2',
                    'version' => 2,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 1,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-2_DPT001_2_PROCESS001.pdf',
                    'pageNum' => 3,
                    'model' => 'MODEL2',
                    'version' => 2,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 2,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-2_DPT001_3_PROCESS001.pdf',
                    'pageNum' => 3,
                    'model' => 'MODEL2',
                    'version' => 2,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 3,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-2_DPT001_4_PROCESS001.pdf',
                    'pageNum' => 3,
                    'model' => 'MODEL2',
                    'version' => 2,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 4,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-2_DPT001_5_PROCESS001.pdf',
                    'pageNum' => 3,
                    'model' => 'MODEL2',
                    'version' => 2,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 5,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-2_DPT002_1_PROCESS002.pdf',
                    'pageNum' => 3,
                    'model' => 'MODEL2',
                    'version' => 2,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 1,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-2_DPT002_2_PROCESS002.pdf',
                    'pageNum' => 3,
                    'model' => 'MODEL2',
                    'version' => 2,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 2,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-2_DPT002_3_PROCESS002.pdf',
                    'pageNum' => 3,
                    'model' => 'MODEL2',
                    'version' => 2,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 3,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-2_DPT002_4_PROCESS002.pdf',
                    'pageNum' => 3,
                    'model' => 'MODEL2',
                    'version' => 2,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 4,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-2_DPT002_5_PROCESS002.pdf',
                    'pageNum' => 3,
                    'model' => 'MODEL2',
                    'version' => 2,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 5,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-2_DPT003_1_PROCESS003.pdf',
                    'pageNum' => 3,
                    'model' => 'MODEL2',
                    'version' => 2,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 1,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-2_DPT003_2_PROCESS003.pdf',
                    'pageNum' => 3,
                    'model' => 'MODEL2',
                    'version' => 2,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 2,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-2_DPT003_3_PROCESS003.pdf',
                    'pageNum' => 3,
                    'model' => 'MODEL2',
                    'version' => 2,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 3,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-2_DPT003_4_PROCESS003.pdf',
                    'pageNum' => 3,
                    'model' => 'MODEL2',
                    'version' => 2,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 4,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL2-2_DPT003_5_PROCESS003.pdf',
                    'pageNum' => 3,
                    'model' => 'MODEL2',
                    'version' => 2,
                    'customer' => 'KH1',
                    'size' => 3,
                    'order' => 5,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                // KH2 model3 ver1
                [
                    'fileName' => 'MODEL3-1_DPT001_1_PROCESS001.pdf',
                    'pageNum' => 4,
                    'model' => 'MODEL3',
                    'version' => 1,
                    'customer' => 'KH2',
                    'size' => 3,
                    'order' => 1,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL3-1_DPT001_2_PROCESS001.pdf',
                    'pageNum' => 4,
                    'model' => 'MODEL3',
                    'version' => 1,
                    'customer' => 'KH2',
                    'size' => 3,
                    'order' => 2,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL3-1_DPT001_3_PROCESS001.pdf',
                    'pageNum' => 4,
                    'model' => 'MODEL3',
                    'version' => 1,
                    'customer' => 'KH2',
                    'size' => 3,
                    'order' => 3,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL3-1_DPT001_4_PROCESS001.pdf',
                    'pageNum' => 4,
                    'model' => 'MODEL3',
                    'version' => 1,
                    'customer' => 'KH2',
                    'size' => 3,
                    'order' => 4,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL3-1_DPT001_5_PROCESS001.pdf',
                    'pageNum' => 4,
                    'model' => 'MODEL3',
                    'version' => 1,
                    'customer' => 'KH2',
                    'size' => 3,
                    'order' => 5,
                    'process' => 'PROCESS001',
                    'depCode' => 'DPT001',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL3-1_DPT002_1_PROCESS002.pdf',
                    'pageNum' => 4,
                    'model' => 'MODEL3',
                    'version' => 1,
                    'customer' => 'KH2',
                    'size' => 3,
                    'order' => 1,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL3-1_DPT002_2_PROCESS002.pdf',
                    'pageNum' => 4,
                    'model' => 'MODEL3',
                    'version' => 1,
                    'customer' => 'KH2',
                    'size' => 3,
                    'order' => 2,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL3-1_DPT002_3_PROCESS002.pdf',
                    'pageNum' => 4,
                    'model' => 'MODEL3',
                    'version' => 1,
                    'customer' => 'KH2',
                    'size' => 3,
                    'order' => 3,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL3-1_DPT002_4_PROCESS002.pdf',
                    'pageNum' => 4,
                    'model' => 'MODEL3',
                    'version' => 1,
                    'customer' => 'KH2',
                    'size' => 3,
                    'order' => 4,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL3-1_DPT002_5_PROCESS002.pdf',
                    'pageNum' => 4,
                    'model' => 'MODEL3',
                    'version' => 1,
                    'customer' => 'KH2',
                    'size' => 3,
                    'order' => 5,
                    'process' => 'PROCESS002',
                    'depCode' => 'DPT002',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL3-1_DPT003_1_PROCESS003.pdf',
                    'pageNum' => 4,
                    'model' => 'MODEL3',
                    'version' => 1,
                    'customer' => 'KH2',
                    'size' => 3,
                    'order' => 1,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL3-1_DPT003_2_PROCESS003.pdf',
                    'pageNum' => 4,
                    'model' => 'MODEL3',
                    'version' => 1,
                    'customer' => 'KH2',
                    'size' => 3,
                    'order' => 2,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL3-1_DPT003_3_PROCESS003.pdf',
                    'pageNum' => 4,
                    'model' => 'MODEL3',
                    'version' => 1,
                    'customer' => 'KH2',
                    'size' => 3,
                    'order' => 3,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL3-1_DPT003_4_PROCESS003.pdf',
                    'pageNum' => 4,
                    'model' => 'MODEL3',
                    'version' => 1,
                    'customer' => 'KH2',
                    'size' => 3,
                    'order' => 4,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
                [
                    'fileName' => 'MODEL3-1_DPT003_5_PROCESS003.pdf',
                    'pageNum' => 4,
                    'model' => 'MODEL3',
                    'version' => 1,
                    'customer' => 'KH2',
                    'size' => 3,
                    'order' => 5,
                    'process' => 'PROCESS003',
                    'depCode' => 'DPT003',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
                ],
            ]);
        }
    }
}
